### ISSUE TITLE
Feature Request: %server_mspt%

### ISSUE THREAD

**Issue by CGDoctor8** [PlaceholderAPI/Server-Expansion#7]
### Type
> What kind of request is this? (Multiple selections possible)

- [x] New function for PlaceholderAPI.  
A new function that developers could use.
- [ ] Change to code (Internal).  
Changes to code that won't affect the end-user.
- [ ] Change to code (External).  
Changes to code that will affect the end-user (breaks stuff).
- [ ] Other: __________ 

### Info
> What is the change?  
Add a new Placeholder called `%server_mspt%` and `%server_mspt_colored%`

MSPT (Milliseconds per tick) is a value that is commonly use for debugging lag in Spigot and Paper Spigot in timing reports, as well as a default metric in the single player f3 menu(See Below). MSPT has the advantage of quantifying how much lag current addons/config/builds degrade or improve the server performance then "It's at 20TPS! that means no lag!" and personally think it would be nice to have it accessible via Placeholder to use in plugin's like Animated Tab or DeluxeMenus for ease of access (compared to only being accessible through the use of using /debug, /timings or specific plugins)

![image](https://user-images.githubusercontent.com/39572468/60692886-49face00-9e95-11e9-8431-b829067be171.png)

Screen shot taken from carpet mod
![image](https://user-images.githubusercontent.com/39572468/60692900-54b56300-9e95-11e9-8c47-d1e46fdc190a.png)

**Comment by ChimneySwift** [comment]
For those on PaperMC, I've [created a fork](https://github.com/ChimneySwift/Server-Expansion) with the following additional placeholders:

```
%server_mspt%
%server_mspt_10s%
%server_mspt_1m%
%server_mspt_colored%
%server_mspt_10s_colored%
%server_mspt_1m_colored%
```

Which give colored and uncolored variants (Same colors as TPS, 0-25ms is green, 25-50 is orange and 50+ is red) of the MSPT averaged over 1 second, 10 seconds and 1 minute depending on which placeholder you use.

Tested on Paper 1.15.2, might also load on Spigot without the new placeholders, but I haven't tested that since I don't need it.

I was originally hoping to implement a spigot-compatible method and make a pull request here, however I was unable to find an easy way to do so without using Paper's timings api. I'm very new to java so I wasn't going to dive into it. Though for those on Paper I'll try keep this mostly updated since I'll need it for my server.

It would still be cool to see this implemented (probably better than I have), MSPT is much more informative to detect laggy areas on a server that is maintaining tps, and it also has the benefit of being near-instant to update.

For those looking for a compiled jar, it's in the repository or you can [download directly here](https://github.com/ChimneySwift/Server-Expansion/raw/master/target/PAPI-Expansion-Server.jar). Place in plugins/PlaceholderAPI/expansions and reload the server.

**Comment by extendedclip** [comment]
We could definitely add these directly to the expansion with a simple check and extra class for the additional placeholders. I’d be down to help

**Comment by extendedclip** [comment]
Do you mind if I integrate what you have?

**Comment by ChimneySwift** [comment]
> Do you mind if I integrate what you have?

Of course, only reason I didn't make a pull request is because it was Paper only, but if that's not an issue go for it.

**Comment by Olexorus** [comment]
I would really like to use the mspt placeholder on my server, what is the current status on this?

**Comment by ChimneySwift** [comment]
> I would really like to use the mspt placeholder on my server, what is the current status on this?

If you'd like you can try my version here https://github.com/ChimneySwift/Server-Expansion (target contains a compiled jar)

I'm currently using it on 1.16.4 with no issues, though it hasn't received any new updates since June 2020. IIRC you might need to disable some options in papi for it to work correctly however.

**Comment by Ikenychi** [comment]
In case you are looking for a 1.17.1 version of this;
i forked ChimneySwift's version and pulled the latest changes.

You can find it at https://github.com/Ikenychi/Server-Expansion.
A pre-built release is provided, as well as build instructions.

**Comment by srnyx** [comment]
@extendedclip When do you plan on adding this?

**Comment by koutsie** [comment]
This would be a good addition.

**Comment by iGabyTM** [comment]
I've looked at the Paper API and it only exposes the ticks from the last 5s. I highly suggest to use the mspt placeholders of https://spark.lucko.me/

**Comment by srnyx** [comment]
> I highly suggest to use the mspt placeholders of [spark.lucko.me](https://spark.lucko.me/)

With spark, would we use `%spark_tickduration%` and/or its variants?

**Comment by iGabyTM** [comment]
I'm not sure, try and see :D

**Comment by Jatc252** [comment]
Hate to revive this issue but just to provide some closure and help for others reading. [Spark](https://spark.lucko.me/), a performance profiler for Minecraft (which is included with [Paper](https://papermc.io/software/paper) now) has a wonderful range of [placeholders](https://spark.lucko.me/docs/misc/Placeholders) that are available ranging from TPS, MSPT (which they call tick duration), and CPU usage of both the java process and entire system.

In regards to this issue, there are three MSPT (tick duration) placeholders available:
- `%spark_tickduration%`: Returns a formatted summary of the average tick durations in the last 10 seconds and 1 minute.
- `%spark_tickduration_10s%`: Returns a formatted representation of the average tick duration in the last 10 seconds.
- `%spark_tickduration_1m%`: Returns a formatted representation of the average tick duration in the last minute.

Below is what `%spark_tickduration%` returned for me on a Paper (1.21.1) server (using [PlaceholderAPI](https://github.com/PlaceholderAPI/PlaceholderAPI)'s `/papi parse` command to parse the placeholder):
![image](https://github.com/user-attachments/assets/8f7e634a-50e5-48d7-8910-6970b512b161)
The 10s and 1m placeholder will just return their respective values as shown above with the red brackets (but without any semicolons).
